// SPDX-FileCopyrightText: Hamza Mahjoubi
// SPDX-License-Identifier: AGPL-3.0-or-later

import NextcloudUI
import SwiftUI

/// Under the body (§5.5): the primary reply, then the smart replies when there are any.
///
/// Smart replies are read from their `serverResult` row (ADR-0067). Pending, empty and
/// failed all show nothing, as the web's silent fetch failure does: an empty row of
/// suggestions is not information.
struct MessageReplyArea: View {
    let model: MessageViewModel
    let reply: (ReplyMode?) -> Void

    @Environment(\.ncTheme) private var theme
    @Environment(\.openComposer) private var openComposer

    private var primaryTitle: String {
        if model.isFollowUp { return String(localized: "Follow up") }
        return model.header?.hasSeveralRecipients == true ? String(localized: "Reply all") : String(localized: "Reply")
    }

    var body: some View {
        VStack(alignment: .leading, spacing: theme.metrics.spacing.tight) {
            HStack(spacing: theme.metrics.spacing.standard) {
                Button(primaryTitle) { reply(nil) }
                    .buttonStyle(.primary)
                if model.offersSmartReplies, let replies = model.smartReplies.value, let id = model.expandedId {
                    ForEach(replies, id: \.self) { text in
                        Button {
                            openComposer(.smartReply(messageId: id, text: text))
                        } label: {
                            Text(verbatim: text).lineLimit(1)
                        }
                        .buttonStyle(.secondary)
                        .help(text)
                    }
                }
            }
            if model.offersSmartReplies, model.smartReplies.value != nil {
                Label {
                    Text("Suggested replies are using AI")
                } icon: {
                    MailSymbol.aiContent.view(size: .small, label: .decorative)
                }
                .font(.caption)
                .foregroundStyle(.secondary)
            }
        }
        .padding(.horizontal, theme.metrics.spacing.loose)
        .padding(.vertical, theme.metrics.spacing.standard)
    }
}

/// The thread summary over the subject (ADR-0067 row): "Summarizing thread…" while pending,
/// the summary when ready, nothing when the server had nothing or failed.
struct ThreadSummaryCard: View {
    let state: ServerResultState<String>

    @Environment(\.ncTheme) private var theme

    var body: some View {
        switch state {
        case .pending:
            NCNoteCard(.info, title: "Thread summary") {
                HStack(spacing: theme.metrics.spacing.standard) {
                    ProgressView().controlSize(.small)
                    Text("Summarizing thread…")
                }
            }
            .padding([.horizontal, .top], theme.metrics.spacing.loose)
        case .ready(let summary):
            NCNoteCard(.info, title: "Thread summary") {
                Text(verbatim: summary).textSelection(.enabled)
                Text("This summary was generated by AI and may contain inaccuracies.")
                    .font(.caption)
            }
            .padding([.horizontal, .top], theme.metrics.spacing.loose)
        case .idle, .empty, .failed:
            EmptyView()
        }
    }
}
